name: Lint, build, & test

on:
  push:
    branches:
    - master
  pull_request:

concurrency:
  # Cancel if I push to the same branch
  cancel-in-progress: true
  # Don't cancel on master
  group: ${{ github.ref == 'refs/heads/master' && format('ci-master-{0}', github.sha) || format('ci-{0}', github.ref) }}

env:
  CARGO_TERM_COLOR: always

jobs:
  lint-build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: test
      run: |
        git show-ref
    - name: Install rust
      run: rustup toolchain install stable --profile minimal
    - name: Cache cargo dependencies
      uses: Swatinem/rust-cache@v2
    - name: Benchmark (PR)
      if: ${{ !cancelled() && (success() || failure()) && github.ref != 'refs/heads/master' }}
      # https://github.com/bheisler/criterion.rs/issues/193#issuecomment-415740713
      run: |
        git checkout ${{ github.ref }}
        git fetch origin master --depth 1
        git checkout master
        cargo bench --bench benchmarks -- --save-baseline base
        git checkout ${{ github.event.pull_request.head.sha }}
        cargo bench --bench benchmarks -- --baseline base | tee benchmark_output.txt
        pwd
        ls
    - name: PR comment with file
      if: ${{ github.ref != 'refs/heads/master' }}
      uses: thollander/actions-comment-pull-request@v2
      with:
        filePath: benchmark_output.txt
