name: Lint, build, & test

on: [ push ]

concurrency: # Cancel if I push to the same branch
  # Don't cancel on master
  group: ${{ github.ref == 'refs/heads/master' && format('ci-master-{0}', github.sha) || format('ci-{0}', github.ref) }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  lint-build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install rust
      run: rustup toolchain install stable --profile minimal
    - uses: Swatinem/rust-cache@v2
    - name: Lint
      run: cargo clippy --verbose --all-targets --all-features -- -D warnings
    - name: Build
      if: ${{ always() }}
      run: cargo build --verbose
    - name: Test
      if: ${{ always() }}
      run: cargo test --verbose
    - name: Benchmark
      if: ${{ always() }}
      run: cargo bench