name: Lint, build, & test

on: [ push ]

concurrency: # Cancel if I push to the same branch
  # Don't cancel on master
  group: ${{ github.ref == 'refs/heads/master' && format('ci-master-{0}', github.sha) || format('ci-{0}', github.ref) }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  lint-build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install rust
      run: rustup toolchain install stable --profile minimal
    - uses: Swatinem/rust-cache@v2
    - name: Lint
      run: cargo clippy --all-targets --all-features -- -D warnings
    - name: Build
      if: ${{ always() }}
      run: cargo build
    - name: Test
      if: ${{ always() }}
      run: cargo test
    - name: Benchmark (master)
      if: ${{ always() && github.ref == 'refs/heads/master' }}
      # https://github.com/bheisler/criterion.rs/issues/193#issuecomment-415740713
      run: |
        cargo bench --bench benchmarks
    - name: Benchmark (PR)
      if: ${{ always() && github.ref != 'refs/heads/master' }}
      # https://github.com/bheisler/criterion.rs/issues/193#issuecomment-415740713
      run: |
        git checkout ${{ github.event.pull_request.base.sha }}
        cargo bench --bench benchmarks -- --save-baseline base
        git checkout ${{ github.event.pull_request.head.sha }}
        cargo bench --bench benchmarks -- --baseline base
