name: Lint, build, & test

on: [ push ]

concurrency:
  # Cancel if I push to the same branch
  cancel-in-progress: true
  # Don't cancel on master
  group: ${{ github.ref == 'refs/heads/master' && format('ci-master-{0}', github.sha) || format('ci-{0}', github.ref) }}

env:
  CARGO_TERM_COLOR: always

jobs:
  lint-build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 50 # this is to make sure we obtain the target base commit
    - name: Install rust
      run: rustup toolchain install stable --profile minimal
    - name: Cache cargo dependencies
      uses: Swatinem/rust-cache@v2
    - name: Lint
      run: cargo clippy --all-targets --all-features -- -D warnings
    - name: Build
      if: ${{ success() || failure() }}
      run: cargo build
    - name: Test
      if: ${{ success() || failure() }}
      run: cargo test
    - name: Benchmark (master)
      if: ${{ !cancelled() && (success() || failure()) && github.ref == 'refs/heads/master' }}
      run: |
        cargo bench --bench benchmarks
    - name: Benchmark (PR)
      if: ${{ !cancelled() && (success() || failure()) && github.ref != 'refs/heads/master' }}
      # https://github.com/bheisler/criterion.rs/issues/193#issuecomment-415740713
      run: |
        git checkout refs/heads/master
        cargo bench --bench benchmarks -- --save-baseline base
        git checkout ${{ github.ref }}
        cargo bench --bench benchmarks -- --baseline base
